### ISSUE TITLE
Question about reconstructions

### ISSUE THREAD

**Issue by alexjc** [Ujjawal-K-Panchal/coshnet#5]
How accurate should the reconstructions be?  I'm trying out `shearrec2D` after the `sheardec2D` and the results aren't as good as I would have expected — even bumping up the number of different shearlets.

Are other filters needed in combination with shearlets to get good reconstructions?

Thanks!

**Comment by alexjc** [comment]
I get much better reconstructions if #6 is fixed, except for the borders of the image.  It's something to do with `sample_wavelet_off_origin` in `construct_shearlet()` not using accurate numbers where it's padded.  I wonder why the authors didn't just calculate `wav_freq` with the offset directly?

**Comment by arsenal9971** [comment]
As I mentioned in #6, since you have found this bug, it is worth trying your approach and the results on the classification task might improve. Now, these shearlets do not have an as good resolution in the reconstruction as the classical compactly supported shearlets see for example [pyshearlab](https://github.com/stefanloock/pyshearlab) since in this case, they are band-limited, having a better resolution in the frequency domain than in the spatial domain. These shearlets are not commonly used to perform tasks in the image domain, but in the frequency domain, such as oriented edge extraction in the sense of the phase-congruency principle. 

Although again, it might be right that it could have something to do with the mentioned functions, I am not so familiar with the technicalities behind their implementation decisions.

**Comment by alexjc** [comment]
Closing this thread too, I think @arsenal9971 your comment in the other thread answered it:
> This construction was actually originally presented in the [paper](https://arxiv.org/pdf/1901.09723.pdf) from the authors of coshrem. At the end of Section 3.1. they say "However, Theorem 3.1 also shows that changing the symmetry properties of a generator by applying the Hilbert transform reduces smoothness in the Fourier domain and thus localization in the time domain."
